# Generated by Django 5.1.2 on 2024-11-01 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_alter_appointment_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='login',
        ),
    ]
