# Generated by Django 5.1.2 on 2024-11-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_appointment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
