# Generated by Django 5.1.2 on 2024-11-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_appointment_gender_alter_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorname',
            field=models.CharField(default='doctor', max_length=20),
        ),
    ]
