# Generated by Django 5.1.2 on 2024-11-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_appointment_doctorname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorname',
            field=models.CharField(max_length=20),
        ),
    ]
